[workspace]
members = [
    "som-core",
    "som-interpreter-bc",
    "som-interpreter-ast",
    "som-lexer",
    "som-parser-core",
    "som-parser-symbols",
    "som-parser-text",
]

[profile.release]
debug=true
