[package]
name = "som-gc"
version = "0.1.0"
description = "A garbage collector for the Simple Object Machine"
authors = ["Nicolas Polomack <nmp21@kent.ac.uk>"]
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
num-bigint = { version = "0.4.3", optional = true }