name: Benchmarks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rebench:
    name: Run and report benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
      - name: Compile SOM interpreter
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p som-interpreter
      - name: Install ReBench
        run: |
          pip install rebench
      - name: Run and report benchmarks
        run: |
          rebench --without-nice --experiment="CI Benchmark Run ID ${GITHUB_RUN_ID}" --branch="${GITHUB_REF}" -c rebench.conf som-rs
